version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "checkout branck"
          command: "git pull"
      - run:
          name: "build"
          command: "cmake -B build && cmake --build build"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - test
      - run:
          name: "test"
          command: "make test"


